swagger: '2.0'
info:
  title: service.hebe.io
  description: Services and Demos around Message Delivery
  version: "1.0.0"
# the domain of the service
host: service.hebe.io
# array of all schemes that your API supports
schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /demo
produces:
  - application/json
  - html/text
paths:
  /iec/jwt/generate:
    get:
      summary: generate a valid jwt for IEC
      security:
       - headerAuth: []
      description: |
        Does generate a valid JWT for IEC.
      parameters:
        - name: email
          in: query
          description: email of the client will be used in the jwt claim clientID.
          required: true
          type: string
        - name: jwtkeyname
          in: query
          description: name of the jwt private key to lookup internally.
          required: true
          type: string
        - name: cookiename
          in: query
          description: name of the cookie which is going to provide the jwt in the client response.
          required: true
          type: string
        - name: hostname
          in: query
          description: used for the cookie domain and also for the jwt claim iss.
          required: true
          type: string
      tags:
        - Result
      responses:
        200:
          description: OK
          examples:
            application/json: {"jwt.iec":"jwt_value"}
          schema:
            type: array
            items:
              $ref: '#/definitions/Result'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Result:
    type: object
    properties:
        jwt:
          example: "jwt_value"
          description: valid IEC jwt.
          type: string
        jwtkeyname:
          example: "jwt_key_name"
          description: name of the jwt private key to lookup internally.
          type: string
        cookiename:
          example: "jwt.iec"
          description: name of the cookie which is going to provide the jwt in the client response.
          type: string
        hostname:
          example: "domain.com"
          description: used for the cookie domain and also for the jwt claim iss.
          type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
securityDefinitions:
  headerAuth:
    type: apiKey
    in: header
    name: X-AUTH-JWT
